name: Update Files List

on:
  push:
    branches:
      - main # change this to the branch you want to trigger the workflow

jobs:
  update-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq # this is a command-line utility for manipulating JSON data

      - name: Generate files.json
        run: |
          cd $GITHUB_WORKSPACE
          ls -1 | grep -v 'files.json' | xargs -I{} sh -c "echo '{\"name\":\"{}\",\"url\":\"{}\"},' >> files.json"
          sed -i '$ s/.$//' files.json # remove the trailing comma
          echo ']' >> files.json # add the closing bracket

      - name: Commit changes
        run: |
          git config --global user.email "raydillanv1@gmail.com"
          git config --global user.name "Dillan V"
          git add $GITHUB_WORKSPACE/files.json
          git commit -m "Update files.json"
          git push
